// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aknbsciqccjqoarwdcwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbmJzY2lxY2NqcW9hcndkY3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzQyMTQsImV4cCI6MjA3NDMxMDIxNH0.E4Ku-yW6SmeEnNbjDgZjHjJ-j8RYQys2Gz-I1MjDY-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});